#!/bin/bash

#####
#       PARSE COMMAND LINE
#####
function usage () {
    echo "Usage: $0 TTI_FILE [-timing ACTION_TIME_FILE] [-o BASENAME]" 1>&2
    echo "" 1>&2
    echo "TTI_FILE                    TTI versus time file generated by readtqtec" 1>&2
    echo "-timing ACTION_TIME_FILE    Timing of tectonic actions generated by tqtec -timing" 1>&2
    echo "-o BASENAME                 Basename for output file (default: temp_vs_time)" 1>&2
    exit 1
}

# Required temperature vs. time file
TTI_FILE="$1"
if [ ! -f $TTI_FILE ]
then
    echo "$0: could not find TTI file \"$TTI_FILE\"" 1>&2
    exit 1
fi
shift

# Optional files
TIMING_FILE=
BASENAME=tti_vs_time
while [ "$1" != "" ]
do
    case $1 in
        -timing) shift; TIMING_FILE=$1;;
        -o) shift; BASENAME=$1;;
    esac
    shift
done


#####
#	SET BOUNDS
#####
# TTI
TMIN="1"
TMAX=`awk '{if (NR>1) print $0}' $TTI_FILE | gmt gmtinfo -C |\
        awk '{for(i=1;i<=NF;i++){printf("%f\n"),$i}}' | gmt gmtinfo -C |\
        awk '{print $2-$2%1+1}'`

# Time
tMIN=`head -1 $TTI_FILE | awk '{print $1}'`
tMAX="0"
dt=`head -1 $TTI_FILE | awk '{print $2}'`

# Tectonic action timing
function plot_tectonic_timing () {
    YMIN=$(echo $LIMS | sed -e "s/-R//" | awk -F/ '{print $3}')
    YMAX=$(echo $LIMS | sed -e "s/-R//" | awk -F/ '{print $4}')
    awk 'BEGIN{print ">"}{
        if ($1=="burial" || $1=="uplift" || $1=="thicken") {
            print ">"
            print '$tMIN'+$3,'$YMIN'
            print '$tMIN'+$4,'$YMIN'
            print '$tMIN'+$4,'$YMAX'
            print '$tMIN'+$3,'$YMAX'
            print '$tMIN'+$3,'$YMIN'
        }
    }' $TIMING_FILE |\
        gmt psxy $PROJ $LIMS -G245 -K -O >> $PSFILE
    awk 'BEGIN{print ">"}{
        if ($1=="thrust") {
            print ">"
            print '$tMIN'+$3,'$YMIN'
            print '$tMIN'+$3,'$YMAX'
        }
    }' $TIMING_FILE |\
        gmt psxy $PROJ $LIMS -W3p,225 -K -O >> $PSFILE
}


#####
#	PLOT TTI VS TIME
#####

# GMT variables
gmt set PS_MEDIA 17ix17i
gmt set MAP_GRID_PEN 0.5p,225,4_4:0

LIMS="-R$tMIN/$tMAX/$TMIN/$TMAX"
tMIN_MODEL=`echo $tMIN | awk '{print -$1}'`
tMAX_MODEL=`echo $tMAX | awk '{print -$1}'`
LIMS_MODEL="-R$tMAX_MODEL/$tMIN_MODEL/$TMIN/$TMAX"

AGE_TIKS=`echo $LIMS | sed -e "s/-R//" | awk -F"/" '{print $1,$2}' |\
          awk '{
              time = $2-$1
              if (time>=50) {dt=10}
              else if (time>=20) {dt=5}
              else if (time>=10) {dt=2}
              else {dt=1}
              print dt
          }'`
TTI_TIKS=`echo $LIMS | sed -e "s/-R//" | awk -F"/" '{print $3,$4}' |\
          awk '{
              temp = $2-$1
              if (temp>=200) {dT=50}
              else if (temp>=100) {dT=20}
              else if (temp>=50) {dT=10}
              else if (temp>=20) {dT=5}
              else if (temp>=10) {dT=2}
              else if (temp>=5) {dT=1}
              else {dT=0.5}
              print dT
          }'`
TTI_TIKS=2

PROJ="-JX8i/6il"

PSFILE="${BASENAME}.ps"


# Colors for each horizon
NCOL=$(sed -ne "2p" $TTI_FILE | awk '{print NF}')
NCOL2=$(echo $NCOL 1.1 | awk '{print $1*$2}')
gmt makecpt -Cmagma -T0/$NCOL2/1 > color_list.cpt
awk '{if(NF==5){print $2}}' color_list.cpt > color_list.tmp


# Initialize plot
gmt psxy -T -K > $PSFILE

# Tectonic timing
if [ "$TIMING_FILE" != "" ]; then plot_tectonic_timing; fi

# Basemap
gmt psbasemap $PROJ $LIMS -Bxa${AGE_TIKS}g${AGE_TIKS}+l"Time Before Present (Ma)" \
    -Bya${TTI_TIKS}g${TTI_TIKS}+l"Time-Temperature Index of Maturity (TTI)" -BWeS -K -O >> $PSFILE
gmt psbasemap $PROJ $LIMS_MODEL -Bxa${AGE_TIKS}+l"Model Time (Ma)" -BN -K -O >> $PSFILE

# TTI values
# Waples, D.W. (1980). Time and Temperature in Petroleum Formation: Application of Lopatin's
#     Method to Petroleum Exploration. AAPG Bulletin 64, 916-926.
for TTI_LBL in 15,Onset_of_oil_generation \
               75,Peak_of_oil_generation \
               160,End_of_oil_generation \
               500,40_degree_oil_preservation_deadline \
               1000,50_degree_oil_preservation_deadline \
               1500,Wet_gas_preservation_deadline \
               65000,Dry_gas_preservation_deadline
do
    TTI_VAL=`echo $TTI_LBL | awk -F, '{print $1}'`
    LBL=`echo $TTI_LBL | awk -F, '{print $2}'`
    echo $LIMS | sed -e "s/-R//" |\
        awk -F/ '{print $1,'$TTI_VAL';print $2,'$TTI_VAL'}' |\
        gmt psxy $PROJ $LIMS -W1p -K -O >> $PSFILE
    echo $LIMS | sed -e "s/-R//" |\
        awk -F/ '{print $1,'$TTI_VAL',"'$LBL'"}' |\
        sed -e "s/_/ /g" |\
        gmt pstext $PROJ $LIMS -F+f10,2+jLB -D0.05i -K -O >> $PSFILE
done

# TTI versus time
for COL in $(seq 1 $NCOL)
do
    COLOR=$(sed -ne "${COL}p" color_list.tmp)
    if [ $COL -eq 1 ]
    then
        awk '{if (NR > 1) print '$tMIN'+(NR-1)*'$dt',$'$COL'}' $TTI_FILE |\
          gmt psxy $PROJ $LIMS -W3p,$COLOR -K -O >> $PSFILE
    else
        awk '{if (NR > 1) print '$tMIN'+(NR-1)*'$dt',$'$COL'}' $TTI_FILE |\
          gmt psxy $PROJ $LIMS -W1p,$COLOR -K -O >> $PSFILE
    fi
done

# Date and time
echo 12,2 LB $(date) | gmt pstext $PROJ $LIMS -F+f+j+cBL -D0.05i -K -O >> $PSFILE

# Finalize
gmt psxy -T -O >> $PSFILE

gmt psconvert $PSFILE -Tf -A
echo "Created file $(basename $PSFILE .ps).pdf"

rm $PSFILE
rm gmt.*
rm color_list.tmp
rm color_list.cpt
