#!/bin/bash

#####
#	PARSE COMMAND LINE
#####
function usage () {
    echo "Usage: $0 DEP_FILE TEMP_FILE [-geotherm GEOTHERM_FILE] [-geotherm:time TIME] [-o BASENAME]" 1>&2
    echo "" 1>&2
    echo "DEP_FILE                    Depth versus time file generated by readtqtec" 1>&2
    echo "TEMP_FILE                   Temperature versus time file generated by readtqtec" 1>&2
    echo "-horizon:time TIME          Plot horizon temp/dep every TIME Ma (default: 10 Ma)" 1>&2
    echo "-geotherm GEOTHERM_FILE     Geotherm generated by tqtec -geotherm (default: plot geotherm at start of model)" 1>&2
    echo "-geotherm:time TIME         Time to plot geotherm in Ma since start of model (option can be repeated)" 1>&2
    echo "-o BASENAME                 Basename for output file (default: temp_vs_dep)" 1>&2
    exit 1
}

# Required depth vs. time file
DEPFILE="$1"
TEMPFILE="$2"
if [ ! -f $DEPFILE ]
then
    echo "$0: could not find depth file \"$DEPFILE\"" 1>&2
    exit 1
fi
if [ ! -f $TEMPFILE ]
then
    echo "$0: could not find temperature file \"$TEMPFILE\"" 1>&2
    exit 1
fi
shift

# Optional arguments
HORIZON_TIME=10
GEOTHERM_FILE=
GEOTHERM_PLOT_TIME=0
BASENAME=temp_vs_dep
while [ "$1" != "" ]
do
    case $1 in
        -horizon:time) shift; HORIZON_TIME=$1;;
        -geotherm) shift; GEOTHERM_FILE=$1;;
        -geotherm:time) shift; GEOTHERM_PLOT_TIME="$GEOTHERM_PLOT_TIME $1";;
        -o) shift; BASENAME=$1;;
    esac
    shift
done


#####
#	SET BOUNDS
#####
# Temperature
TMIN="0"
TMAX=`awk '{if (NR>1) print $0}' $TEMPFILE | gmt gmtinfo -C |\
        awk '{for(i=1;i<=NF;i++){printf("%f\n"),$i}}' | gmt gmtinfo -C |\
        awk '{print $2-$2%20+20}'`

# Depth
ZMIN=`awk '{if (NR>1) print $0}' $DEPFILE | gmt gmtinfo -C |\
      awk '{for(i=1;i<=NF;i++){printf("%f\n"),$i}}' | gmt gmtinfo -C |\
      awk '{print $1-$1%10-10}'`
ZMAX=`awk '{if (NR>1) print $0}' $DEPFILE | gmt gmtinfo -C |\
      awk '{for(i=1;i<=NF;i++){printf("%f\n"),$i}}' | gmt gmtinfo -C |\
      awk '{print $2-$2%10+10}'`
ZMAX0="0"

# Starting time
tMIN=`head -1 $DEPFILE | awk '{print $1}'`
dt=`head -1 $DEPFILE | awk '{print $2}'`


#####
#	PLOT TEMPERATURE VS DEPTH
#####

# GMT variables
gmt set PS_MEDIA 17ix17i
gmt set MAP_GRID_PEN 0.5p,225,4_4:0


LIMS="-R$TMIN/$TMAX/$ZMIN/$ZMAX0"
PROJ="-JX6i/6i -P"

DEP_TIKS=`echo $LIMS | sed -e "s/-R//" | awk -F"/" '{print $3,$4}' |\
          awk '{
              relief = $2-$1
              if (relief>=50) {dz=10}
              else if (relief>=20) {dz=5}
              else if (relief>=10) {dz=2}
              else if (relief>=5) {dz=1}
              else {dz=0.5}
              print dz
          }'`
TEMP_TIKS=`echo $LIMS | sed -e "s/-R//" | awk -F"/" '{print $1,$2}' |\
          awk '{
              temp = $2-$1
              if (temp>=200) {dT=50}
              else if (temp>=100) {dT=20}
              else if (temp>=50) {dT=10}
              else if (temp>=20) {dT=5}
              else if (temp>=10) {dT=2}
              else if (temp>=5) {dT=1}
              else {dT=0.5}
              print dT
          }'`

PSFILE="${BASENAME}.ps"

# Colors for horizons
NCOL=$(sed -ne "2p" $DEPFILE | awk '{print NF}')
NCOL2=$(echo $NCOL 1.1 | awk '{print $1*$2}')
gmt makecpt -Cmagma -T0/$NCOL2/1 | awk '{if(NF==5){print $2}}' > color_list.tmp


# Initialize plot
gmt psxy -T -K > $PSFILE

# Basemap
gmt psbasemap $PROJ $LIMS -Bxa${TEMP_TIKS}g${TEMP_TIKS}+l"Temperature (\260C)" -Bya${DEP_TIKS}g${DEP_TIKS}+l"Depth (km)" -BWeSn -K -O >> $PSFILE

# Geotherm
if [ "$GEOTHERM_FILE" != "" ]
then
    for T in $GEOTHERM_PLOT_TIME
    do
        T2=$(echo $T $tMIN | awk '{print $1+$2}')
        echo "Plotting geotherm at $T Ma since start of model, $T2 Ma until end of model"
        awk '{
            if (/>/) {
                p = 0
                if ($3==0 && $4=='$T') {
                    p = 1
                    print "> -W1p"
                } else if ($4=='$T') {
                    p = 1
                    print "> -W0.5p,105"
                }
            } else if (p==1) {
                print $1,-$2
            }
        }' $GEOTHERM_FILE > geotherm_$T.tmp
        WC_GEOTHERM=$(wc geotherm_$T.tmp | awk '{print $1}')
        if [ $WC_GEOTHERM -le 0 ]
        then
            echo "Could not find a geotherm output at the specified time"
        else
            gmt psxy geotherm_$T.tmp $PROJ $LIMS -K -O >> $PSFILE
            awk '{if(NR>1&&($2<='$ZMIN'||$1>='$TMAX')){print $1,$2,"8,2 LM '$T2' Ma";exit}}' geotherm_$T.tmp |\
                gmt pstext $PROJ $LIMS -F+f+j -D0.025i/0 -Gwhite -N -K -O >> $PSFILE
        fi
    done
fi


# Temperature versus depth
for i in $(seq 1 $NCOL)
do
    COLOR=$(sed -ne "${i}p" color_list.tmp | awk '{print $1}')
    # Plot curves
    paste $TEMPFILE $DEPFILE |\
        awk '{if (NR > 1) print $'$i',$('$i'+'$NCOL')}' |\
        gmt psxy $PROJ $LIMS -W1p,$COLOR -K -O >> $PSFILE
    # Large dot at 0 Ma
    paste $TEMPFILE $DEPFILE |\
        awk '{if (NR == 2) print $'$i',$('$i'+'$NCOL')}' |\
        gmt psxy $PROJ $LIMS -Sc0.10i -G$COLOR -W0.5p -K -O >> $PSFILE
    # Dots every 10 Ma
    paste $TEMPFILE $DEPFILE |\
        awk '{if (NR>1 && ((NR-1)*'$dt')%'$HORIZON_TIME' == 0) print $'$i',$('$i'+'$NCOL')}' |\
        gmt psxy $PROJ $LIMS -Sc0.05i -G$COLOR -W0.5p -K -O >> $PSFILE
done


# Indicate how often horizons are plotted as dots
echo $LIMS | sed -e "s/-R//" |\
    awk -F/ '{print $2,$4}' |\
    gmt psxy $PROJ $LIMS -Sc0.05i -G$COLOR -W0.5p -D-3.1i/-0.2i -K -O >> $PSFILE
echo $LIMS | sed -e "s/-R//" |\
    awk -F/ '{print $2,$4,"Tracked horizons plotted every '$HORIZON_TIME' Ma"}' |\
    gmt pstext $PROJ $LIMS -F+f12,0+jLM -D-3.0i/-0.2i -K -O >> $PSFILE


# Date and time
echo 12,2 LB $(date) | gmt pstext $PROJ $LIMS -F+f+j+cBL -D0.05i -K -O >> $PSFILE

# Finalize
gmt psxy -T -O >> $PSFILE

gmt psconvert $PSFILE -Tf -A
echo "Created file $(basename $PSFILE .ps).pdf"

rm $PSFILE
rm gmt.*
rm color_list.tmp
