#!/bin/bash

#####
#	PARSE COMMAND LINE
#####
function usage () {
    echo "Usage: $0 DEP_FILE [-timing ACTION_TIME_FILE] [-o BASENAME]" 1>&2
    echo "" 1>&2
    echo "DEP_FILE                    Depth versus time file generated by readtqtec" 1>&2
    echo "-timing ACTION_TIME_FILE    Timing of tectonic actions generated by tqtec -timing" 1>&2
    echo "-o BASENAME                 Basename for output file (default: dep_vs_time)" 1>&2
    exit 1
}

# Required depth vs. time file
DEPFILE="$1"
if [ ! -f $DEPFILE ]
then
    echo "$0: could not find depth file \"$DEPFILE\"" 1>&2
    exit 1
fi
shift

# Optional files
TIMING_FILE=
BASENAME=dep_vs_time
while [ "$1" != "" ]
do
    case $1 in
        -timing) shift; TIMING_FILE=$1;;
        -o) shift; BASENAME=$1;;
    esac
    shift
done


#####
#	SET BOUNDS
#####
# Depth
ZMIN=`awk '{if (NR>1) print $0}' $DEPFILE | gmt gmtinfo -C |\
      awk '{for(i=1;i<=NF;i++){printf("%f\n"),$i}}' | gmt gmtinfo -C |\
      awk '{print $1-$1%10-10}'`
ZMAX=`awk '{if (NR>1) print $0}' $DEPFILE | gmt gmtinfo -C |\
      awk '{for(i=1;i<=NF;i++){printf("%f\n"),$i}}' | gmt gmtinfo -C |\
      awk '{print $2-$2%10+10}'`

# Time
tMIN=`head -1 $DEPFILE | awk '{print $1}'`
tMAX="0"
dt=`head -1 $DEPFILE | awk '{print $2}'`

# Tectonic action timing
function plot_tectonic_timing () {
    YMIN=$(echo $LIMS | sed -e "s/-R//" | awk -F/ '{print $3}')
    YMAX=$(echo $LIMS | sed -e "s/-R//" | awk -F/ '{print $4}')
    awk 'BEGIN{print ">"}{
        if ($1=="burial" || $1=="uplift") {
            print ">"
            print '$tMIN'+$3,'$YMIN'
            print '$tMIN'+$4,'$YMIN'
            print '$tMIN'+$4,'$YMAX'
            print '$tMIN'+$3,'$YMAX'
            print '$tMIN'+$3,'$YMIN'
        }
    }' $TIMING_FILE |\
        gmt psxy $PROJ $LIMS -G245 -K -O >> $PSFILE
    awk 'BEGIN{print ">"}{
        if ($1=="thrust") {
            print ">"
            print '$tMIN'+$3,'$YMIN'
            print '$tMIN'+$3,'$YMAX'
        }
    }' $TIMING_FILE |\
        gmt psxy $PROJ $LIMS -W3p,225 -K -O >> $PSFILE
}


#####
#	PLOT DEPTH VS TIME
#####

# GMT variables
gmt set PS_MEDIA 17ix17i
gmt set MAP_GRID_PEN 0.5p,225,4_4:0

LIMS="-R$tMIN/$tMAX/$ZMIN/$ZMAX"
tMIN_MODEL=`echo $tMIN | awk '{print -$1}'`
tMAX_MODEL=`echo $tMAX | awk '{print -$1}'`
LIMS_MODEL="-R$tMAX_MODEL/$tMIN_MODEL/$ZMIN/$ZMAX"

AGE_TIKS=`echo $LIMS | sed -e "s/-R//" | awk -F"/" '{print $1,$2}' |\
          awk '{
              time = $2-$1
              if (time>=50) {dt=10}
              else if (time>=20) {dt=5}
              else if (time>=10) {dt=2}
              else {dt=1}
              print dt
          }'`
DEP_TIKS=`echo $LIMS | sed -e "s/-R//" | awk -F"/" '{print $3,$4}' |\
          awk '{
              relief = $2-$1
              if (relief>=50) {dz=10}
              else if (relief>=20) {dz=5}
              else if (relief>=10) {dz=2}
              else if (relief>=5) {dz=1}
              else {dz=0.5}
              print dz
          }'`

PROJ="-JX8i/6i"

PSFILE="${BASENAME}.ps"


# Colors for each horizon
NCOL=$(sed -ne "2p" $DEPFILE | awk '{print NF}')
NCOL2=$(echo $NCOL 1.1 | awk '{print $1*$2}')
gmt makecpt -Cmagma -T0/$NCOL2/1 | awk '{if(NF==5){print $2}}' > color_list.tmp


# Initialize plot
gmt psxy -T -K > $PSFILE

# Tectonic timing
if [ "$TIMING_FILE" != "" ]; then plot_tectonic_timing; fi

# Basemap
gmt psbasemap $PROJ $LIMS -Bxa${AGE_TIKS}g${AGE_TIKS}+l"Time Before Present (Ma)" -Bya${DEP_TIKS}g${DEP_TIKS}+l"Depth (km)" -BWeS -K -O >> $PSFILE
gmt psbasemap $PROJ $LIMS_MODEL -Bxa${AGE_TIKS}+l"Model Time (Ma)" -BN -K -O >> $PSFILE

# Depth versus time
for COL in $(seq 1 $NCOL)
do
    COLOR=$(sed -ne "${COL}p" color_list.tmp)
    if [ $COL -eq 1 ]
    then
        awk 'BEGIN{g=1}{
            if (NR == 1) {print "> -W3p,'$COLOR'"}
            if (NR > 1) {
                if (g==1 && $'$COL'>0) {
                    g = 0
                    print "> -W3p,'$COLOR'@80"
                }
                if (g==0 && $'$COL'<=0) {
                    g = 1
                    print "> -W3p,'$COLOR'"
                }
                print '$tMIN'+(NR-1)*'$dt',$'$COL'
            }
        }' $DEPFILE |\
            gmt psxy $PROJ $LIMS -K -O >> $PSFILE
    else
        awk 'BEGIN{g=1}{
            if (NR == 1) {print "> -W1p,'$COLOR'"}
            if (NR > 1) {
                if (g==1 && $'$COL'>0) {
                    g = 0
                    print "> -W1p,'$COLOR'@80"
                }
                if (g==0 && $'$COL'<=0) {
                    g = 1
                    print "> -W1p,'$COLOR'"
                }
                print '$tMIN'+(NR-1)*'$dt',$'$COL'
            }
        }' $DEPFILE |\
            gmt psxy $PROJ $LIMS -K -O >> $PSFILE
    fi
done

# Zero depth line
gmt psxy $PROJ $LIMS -W1p,105,12_4:0 -K -O >> $PSFILE << EOF
 $tMIN 0
 $tMAX 0
EOF

# Date and time
echo 12,0 LB $(date) | gmt pstext $PROJ $LIMS -F+f+j+cBL -D0.05i -K -O >> $PSFILE

# Finalize
gmt psxy -T -O >> $PSFILE

gmt psconvert $PSFILE -Tf -A
echo "Created file $(basename $PSFILE .ps).pdf"

rm $PSFILE
rm gmt.*
rm color_list.tmp
